/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTitleRouteImport } from './routes/api/title'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTitleRoute = ApiTitleRouteImport.update({
  id: '/api/title',
  path: '/api/title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/title': typeof ApiTitleRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/title': typeof ApiTitleRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/title': typeof ApiTitleRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/title' | '/api/public/chat' | '/api/public/image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/title' | '/api/public/chat' | '/api/public/image'
  id: '__root__' | '/' | '/api/title' | '/api/public/chat' | '/api/public/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTitleRoute: typeof ApiTitleRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/title': {
      id: '/api/title'
      path: '/api/title'
      fullPath: '/api/title'
      preLoaderRoute: typeof ApiTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTitleRoute: ApiTitleRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
